spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/restaurant}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: ${RABBIT_USER:ulysses}
    password: ${RABBIT_PASSWORD:senha123}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5000
          multiplier: 2
          max-interval: 10000
        concurrency: 3
        max-concurrency: 5
springdoc:
  api-docs:
    enabled: 'true'
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 8082
  servlet:
    context-path: /videoprocessing
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    beans:
      cache:
        time-to-live: 10s
  health:
    defaults:
      enabled: false
    db:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8080/realms/auth
            jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

    # JWT Configuration
    jwt:
      auth:
        converter:
          resource-id: auth-client
          principal-attribute: principal_username

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:admin}
  secret-key: ${MINIO_SECRET_KEY:admin123}
  bucket-name: ${MINIO_BUCKET_NAME:videos-hackaton}